apiVersion: v1
kind: Service
metadata:
  name: my-java-app-service
spec:
  type: NodePort
  selector:
    app: my-java-app
  ports:
  - port: 80           # The port that the service will expose
    targetPort: 8082   # The port on the container (Tomcat)
    nodePort: 30001    # Optional: Specify a node port or let Kubernetes assign one
